/**
 * SURAKSHA Emergency Simulation Engine
 * Allows disaster response authorities to test operational drills, team dispatches,
 * and geofenced warnings under realistic simulated meteorological conditions.
 * All simulation data is strictly flagged with isSimulation: true.
 */

import { simulationStateCollection, alertsCollection, sosRequestsCollection, auditLogsCollection } from '../database/store';
import { SimulationState } from '../../src/types';

export function getSimulationState(): SimulationState {
  const existing = simulationStateCollection.getById('singleton_sim_state');
  if (existing) return existing;

  const defaultState: SimulationState = {
    id: 'singleton_sim_state',
    isActive: false,
    currentScenario: 'NORMAL',
    simulatedRainfallMm: 4,
    simulatedWindSpeedKmH: 14,
    simulatedWaterLevelMeters: 0.1,
    simulatedRiskScore: 18,
    activeAlertCount: 1,
    simulatedSosCount: 0
  } as any;

  return simulationStateCollection.insert(defaultState as any);
}

export function activateScenario(
  scenario: 'NORMAL' | 'HEAVY_RAIN' | 'FLOOD' | 'CYCLONE' | 'CRITICAL_FLOOD' | 'LANDSLIDE',
  actor: { id: string; name: string; role: string }
): SimulationState {
  let rainfall = 4;
  let wind = 14;
  let waterLevel = 0.1;
  let riskScore = 18;

  if (scenario === 'HEAVY_RAIN') {
    rainfall = 48;
    wind = 32;
    waterLevel = 0.6;
    riskScore = 58;
  } else if (scenario === 'FLOOD') {
    rainfall = 88;
    wind = 45;
    waterLevel = 1.4;
    riskScore = 78;
  } else if (scenario === 'CYCLONE') {
    rainfall = 110;
    wind = 135;
    waterLevel = 1.9;
    riskScore = 92;
  } else if (scenario === 'CRITICAL_FLOOD') {
    rainfall = 160;
    wind = 60;
    waterLevel = 2.8;
    riskScore = 96;
  } else if (scenario === 'LANDSLIDE') {
    rainfall = 95;
    wind = 30;
    waterLevel = 0.8;
    riskScore = 84;
  }

  const newState: SimulationState = {
    isActive: scenario !== 'NORMAL',
    currentScenario: scenario,
    simulatedRainfallMm: rainfall,
    simulatedWindSpeedKmH: wind,
    simulatedWaterLevelMeters: waterLevel,
    simulatedRiskScore: riskScore,
    activeAlertCount: scenario !== 'NORMAL' ? 2 : 1,
    simulatedSosCount: scenario !== 'NORMAL' ? 3 : 0,
    startedAt: new Date().toISOString(),
    startedBy: actor.name
  };

  simulationStateCollection.update('singleton_sim_state', newState as any);

  // If scenario is active, seed a simulated alert
  if (scenario !== 'NORMAL') {
    const simAlertId = `sim-alert-${Date.now()}`;
    alertsCollection.insert({
      id: simAlertId,
      disasterType: scenario === 'CYCLONE' ? 'CYCLONE' : 'FLOOD',
      title: `[SIMULATION DRILL] Severe ${scenario.replace('_', ' ')} Warning`,
      message: `SIMULATION DRILL FOR RESPONSE TEAMS: Rapid waterlogging simulated across Visakhapatnam coastal lowlines. Evacuate low zones.`,
      severity: riskScore > 80 ? 'CRITICAL' : 'HIGH',
      affectedArea: 'Visakhapatnam Urban District (SIMULATED ZONE)',
      latitude: 17.7200,
      longitude: 83.3100,
      radiusKm: 25,
      safetyInstructions: [
        'Move to higher ground immediately (SIMULATION).',
        'Avoid flooded roads and storm nullahs.',
        'Follow designated evacuation signs.'
      ],
      recommendedAction: 'Move to nearest open relief shelter immediately.',
      recommendedShelterId: 'shelter-vskp-01',
      recommendedShelterName: 'Andhra University Relief Hub & Gymnasium',
      languages: ['en', 'te', 'hi'],
      issuedAt: new Date().toISOString(),
      expiresAt: new Date(Date.now() + 3600000 * 6).toISOString(),
      issuedByAuthorityId: actor.id,
      authorityName: actor.name,
      status: 'ACTIVE',
      isSimulation: true,
      smsStats: {
        targetedUsers: 540,
        sent: 0,
        pending: 0,
        failed: 540 // Honest: simulation does not bill real phone numbers
      }
    } as any);

    // Seed simulated SOS
    sosRequestsCollection.insert({
      id: `SOS-SIM-991`,
      userId: 'user-sim-01',
      userName: 'Ramesh Kumar (Simulated Drill)',
      userPhone: '+91 98765 00001',
      latitude: 17.7125,
      longitude: 83.3240,
      accuracy: 10,
      areaDescription: 'Ground floor inundated near Beach Road (Simulated)',
      emergencyType: 'RESCUE',
      peopleCount: 4,
      message: 'SIMULATION DRILL: Simulated family trapped due to simulated 1.2m water level.',
      medicalAssistanceRequired: false,
      status: 'RECEIVED',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      statusHistory: [
        {
          status: 'RECEIVED',
          timestamp: new Date().toISOString(),
          note: 'Simulated SOS generated by disaster exercise commander.'
        }
      ],
      isSimulation: true
    } as any);
  } else {
    // Remove simulation alerts and SOS
    const allAlerts = alertsCollection.getAll();
    allAlerts.filter(a => a.isSimulation).forEach(a => alertsCollection.delete(a.id));
    const allSos = sosRequestsCollection.getAll();
    allSos.filter(s => s.isSimulation).forEach(s => sosRequestsCollection.delete(s.id));
  }

  auditLogsCollection.insert({
    id: `audit-${Date.now()}`,
    actorId: actor.id,
    actorName: actor.name,
    actorRole: actor.role,
    action: 'EMERGENCY_SIMULATION_TRIGGERED',
    targetCollection: 'simulation_state',
    details: `Triggered simulation drill scenario: ${scenario} by ${actor.name}.`,
    timestamp: new Date().toISOString(),
    status: 'SUCCESS'
  });

  return newState;
}
